/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.116
 * Generated at: 2026-05-20 07:20:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import in.co.rays.proj4.controller.FacultyListCtl;
import in.co.rays.proj4.bean.FacultyBean;
import in.co.rays.proj4.util.DataUtility;
import in.co.rays.proj4.util.ServletUtility;
import java.util.List;
import java.util.Iterator;
import in.co.rays.proj4.controller.ORSView;
import in.co.rays.proj4.bean.UserBean;

public final class FacultyListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1779260448261L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(12);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.FacultyBean");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.rays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.rays.proj4.util.DataUtility");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("in.co.rays.proj4.controller.FacultyListCtl");
    _jspx_imports_classes.add("in.co.rays.proj4.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Faculty List</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/logo.png\" sizes=\"16x16\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" \r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"/ORSProject-04/js/checkbox.js\"></script>\r\n");
      out.write("<script src=\"/ORSProject-04/js/datepicker.js\"></script>\r\n");
      out.write("<link rel = \"icon\" type = \"image/jpg\" href =\"");
      out.print(ORSView.APP_CONTEXT );
      out.write("/image/logo.png\" sizes =\"16*16\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

	UserBean user = (UserBean) session.getAttribute("user");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	if (user != null) {
	
      out.write("\r\n");
      out.write("	<h3>\r\n");
      out.write("		Hi,\r\n");
      out.write("		");
      out.print(user.getFirstName());
      out.write("\r\n");
      out.write("		(");
      out.print(session.getAttribute("role"));
      out.write(")\r\n");
      out.write("	</h3>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.LOGIN_CTL + "?operation=Logout");
      out.write("\"><b>Logout</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\"><b>My Profile</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"ChangePasswordCtl\"><b>Change Password</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\"><b>Add Role</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\"><b>Role List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\"><b>Add User</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\"><b>User List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\"><b>Add College</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\"><b>College List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><b>Add Course</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.COURSE_CTL);
      out.write("\"><b>Course List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\"><b>Add Student</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\"><b>Student List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\"><b>Add Faculty</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\"><b>Faculty List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\"><b>Add Marksheet</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\"><b>Marksheet List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\"><b>Get Marksheet</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\"><b>Marksheet\r\n");
      out.write("			Merit List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\"><b>Add Timetable</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\"><b>Timetable List</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a target=\"blank\" href=\"");
      out.print(ORSView.JAVA_DOC);
      out.write("\"><b>Java Doc</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	");

	} else {
	
      out.write("\r\n");
      out.write("	<h3>Hi, Guest</h3>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\"><b>Welcome</b></a>\r\n");
      out.write("	<b>|</b>\r\n");
      out.write("	<a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\"><b>Login</b></a>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div align=\"center\">\r\n");
      out.write("		<h1 align=\"center\" style=\"margin-bottom: -15; color: navy;\">Faculty List</h1>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"height: 15px; margin-bottom: 12px\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\r\n");
      out.write("			</h3>\r\n");
      out.write("			<h3>\r\n");
      out.write("				<font color=\"green\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\r\n");
      out.write("			</h3>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<form action=\"");
      out.print(ORSView.FACULTY_LIST_CTL);
      out.write("\" method=\"post\">\r\n");
      out.write("			");

				int pageNo = ServletUtility.getPageNo(request);
				int pageSize = ServletUtility.getPageSize(request);
				int index = ((pageNo - 1) * pageSize) + 1;
				int nextPageSize = DataUtility.getInt(request.getAttribute("nextListSize").toString());

				List<FacultyBean> list = (List<FacultyBean>) ServletUtility.getList(request);
				Iterator<FacultyBean> it = list.iterator();

				if (list.size() != 0) {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\">\r\n");
      out.write("			<input type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("			<table style=\"width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\">\r\n");
      out.write("						<label><b>First Name :</b></label>\r\n");
      out.write("						<input type=\"text\" name=\"firstName\" placeholder=\"Enter First Name\" value=\"");
      out.print(ServletUtility.getParameter("firstName", request));
      out.write("\">&emsp;\r\n");
      out.write("						<label><b>Last Name :</b></label>\r\n");
      out.write("						<input type=\"text\" name=\"lastName\" placeholder=\"Enter Last Name\" value=\"");
      out.print(ServletUtility.getParameter("lastName", request));
      out.write("\">&emsp;\r\n");
      out.write("						<label><b>Email Id :</b></label>\r\n");
      out.write("						<input type=\"text\" name=\"email\" placeholder=\"Enter Email Id\" value=\"");
      out.print(ServletUtility.getParameter("email", request));
      out.write("\">&emsp;\r\n");
      out.write("						<input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_SEARCH);
      out.write("\">&nbsp;\r\n");
      out.write("						<input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_RESET);
      out.write("\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<table border=\"1\" style=\"width: 100%; border: groove;\">\r\n");
      out.write("				<tr style=\"background-color: #e1e6f1e3;\">\r\n");
      out.write("					<th><input type=\"checkbox\" id=\"selectall\" /></th>\r\n");
      out.write("					<th>S.No</th>\r\n");
      out.write("					<th>First Name</th>\r\n");
      out.write("					<th>Last Name</th>\r\n");
      out.write("					<th>Email Id</th>\r\n");
      out.write("					<th>College Name</th>\r\n");
      out.write("					<th>Course Name</th>\r\n");
      out.write("					<th>Subject Name</th>\r\n");
      out.write("					<th>Gender</th>\r\n");
      out.write("					<th>Mobile No</th>\r\n");
      out.write("					<th>Date of Birth</th>\r\n");
      out.write("					<th>Edit</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				");

					while (it.hasNext()) {
						FacultyBean bean = it.next();
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"text-align: center;\"><input type=\"checkbox\" class=\"case\" name=\"ids\" value=\"");
      out.print(bean.getId());
      out.write("\"></td>\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getFirstName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getLastName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: lowercase;\">");
      out.print(bean.getEmail());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getCollegeName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getCourseName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getSubjectName());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center; text-transform: capitalize;\">");
      out.print(bean.getGender());
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(bean.getMobileNo());
      out.write("</td>\r\n");
      out.write("					");

						SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
						String date = sdf.format(bean.getDob());
					
      out.write("\r\n");
      out.write("					<td style=\"text-align: center;\">");
      out.print(date);
      out.write("</td>\r\n");
      out.write("					<td style=\"text-align: center;\"><a href=\"FacultyCtl?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			<table style=\"width: 100%\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td style=\"width: 25%\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_PREVIOUS);
      out.write('"');
      out.write(' ');
      out.print(pageNo > 1 ? "" : "disabled");
      out.write("></td>\r\n");
      out.write("					<td align=\"center\" style=\"width: 25%\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_NEW);
      out.write("\"></td>\r\n");
      out.write("					<td align=\"center\" style=\"width: 25%\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_DELETE);
      out.write("\"></td>\r\n");
      out.write("					<td style=\"width: 25%\" align=\"right\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_NEXT);
      out.write('"');
      out.write(' ');
      out.print(nextPageSize != 0 ? "" : "disabled");
      out.write("></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("\r\n");
      out.write("			");

				}
				if (list.size() == 0) {
			
      out.write("\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"right\"><input type=\"submit\" name=\"operation\" value=\"");
      out.print(FacultyListCtl.OP_BACK);
      out.write("\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
